### ISSUE TITLE
🚀 Feature: contribute this to otel

### ISSUE THREAD

**Issue by gyliu513** [traceloop/openllmetry#213]
### Which component is this feature for?

All Packages

### 🔖 Feature description

I can see https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation already have some python instrumentation code, any plan to upstream this to otel? Thanks

### 🎤 Why is this feature needed ?

otel is the official repo for all instrumentations

### ✌️ How do you aim to achieve this?

move all repos to https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nirga** [comment]
Hey @gyliu513 thanks for this! 
We're still contemplating whether this needs to be officially part of OpenTelemetry or an official extension. We're also in the [process of joining CNCF](https://github.com/cncf/sandbox/issues/67). 
The main reasons are that to get proper observability for gen-AI applications, we needed to extend on the semantic conventions as defined in the official otel package, and adding the needed extensions is still [in discussion](https://github.com/open-telemetry/semantic-conventions/pull/483). We're also doing something that is a bit "unorthodox" in the otel community which is sending prompts as span attributes - and this is also [under discussion](https://github.com/open-telemetry/oteps/pull/234). 

Having said that, since this is still 100% compatible with OpenTelemetry, I don't think that the fact that this is outside of the otel-contrib package should make a difference (and we're not even the first ones doing that).

**Comment by nirga** [comment]
Yeah, I'll keep it this open for reference for future inquiries

**Comment by nirga** [comment]
(See #236)
