### ISSUE TITLE
🚀 Feature: Support Haystack v2

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#640]
### Which component is this feature for?

Haystack Instrumentation

### 🔖 Feature description

Upgrade our instrumentation to support the new Haystack v2 APIs

### 🎤 Why is this feature needed ?

-

### ✌️ How do you aim to achieve this?

-

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by mayankagarwals** [comment]
Hey @nirga! 

That makes sense, I've started looking into this!

**Comment by mayankagarwals** [comment]
Hi @nirga !

I had a couple questions I could use clarity on 

1. PromptNode alternative in haystack V2: 
From my understanding, haystack moves away from the concept of PromptNode in v2. 
In Haystack V2, you can create a custom component that can do any task from generation to retrieval . So is it okay to drop the wrapper for haystack.nodes.prompt.prompt_node? 

2. EmbeddingRetriever alternative in haystack V2: 
Similar reasoning: Haystack moves away from the concept of a generic embedding retriever. 
It supports having custom components and gives a bunch of specific document store - retreivers 

One possible approach I see to the problem is 
a. Add wrappers for all existing generators/retreivers 
b. Add wrapper for custom components. 

Do let me know your thoughts. You can refer to my pull request as it has implementation for other wrappers.

**Comment by nirga** [comment]
Yep @mayankagarwals you can remove support for both!

**Comment by mayankagarwals** [comment]
That's great @nirga. Thanks 

Can you help me with the command to test 
```
openllmetry/packages/opentelemetry-instrumentation-haystack/tests/conftest.py 
openllmetry/packages/opentelemetry-instrumentation-haystack/tests/disabled_test_simple_pipeline.py 
```

Looks like these use vcr plugins. The pytest command isn't picking it up.

**Comment by nirga** [comment]
You need to change the file name and removed the disabled prefix

**Comment by mayankagarwals** [comment]
Ah, was wondering why is it called disabled and the GitHub workflow also excludes it haha. Thanks for clarifying, saved a ton of time!

**Comment by mayankagarwals** [comment]
Hi @nirga!
So I've fixed the test but there seems to be a decoding issue with respect to cassette. Would it be possible for you to re-record it? I'm not sure what exactly is breaking there and the issue should resolve anyway if the casette is re-recorded and re-versioned

**Comment by mayankagarwals** [comment]
For reference, this is the error: https://gist.github.com/mayankagarwals/457c8a51032a3bef8276e7737332963a

**Comment by mayankagarwals** [comment]
Hi @nirga , 

Small update. I have tested the current implementation using gpt-3.5-turbo as I had existing api key for it. 
Can you please run `pytest --record-mode=rewrite` and commit the casette file? That will make sure the casette change uses the same model as before. TIA!
